Added logging changing model properties. Closed #8
TopAcademy2022/music-store pull request #14
Opened 2024-11-21 17:25 UTC by artemqdh

2024-11-21 17:32 UTC, TopAcademy2022 commented on Program/Program.cs
Remove this file.

2024-11-21 17:32 UTC, TopAcademy2022 commented on Program/Program.csproj
Remove this file.

2024-11-21 17:33 UTC, TopAcademy2022 commented on music-store.sln
Reverse changes in file.

2024-11-21 17:33 UTC, TopAcademy2022 commented on music-store/Models/Entities/MusicBand.cs
Reverse changes in file.

2024-11-21 17:35 UTC, TopAcademy2022 commented on music-store/Models/Entities/VinylRecord.cs
> +		private static readonly string LogFilePath = "Logs/changes.log";
Relocate this line.

2024-11-21 17:35 UTC, TopAcademy2022 commented on music-store/Models/Entities/VinylRecord.cs
Not created private fields.

2024-11-21 17:36 UTC, TopAcademy2022 commented on music-store/Models/Entities/VinylRecord.cs
> +		private static void LogChange(string propertyName, string oldValue, string newValue)
Using ILogger.

2024-11-21 17:36 UTC, TopAcademy2022 commented on music-store/Models/Entities/MusicGenre.cs
Reverse changes in file.

2024-11-21 17:36 UTC, TopAcademy2022 commented on music-store/Models/Entities/MusicPublisher.cs
Reverse changes in file.

2024-11-25 18:12 UTC, TopAcademy2022 requested changes
Use type T class.

2024-11-26 18:20 UTC, artemqdh commented on Program/Program.cs
delete program.cs? and program.csproj?

2024-11-28 16:33 UTC, TopAcademy2022 commented on Program/Program.cs
Yes.

2024-11-28 16:38 UTC, TopAcademy2022 requested changes

2024-11-28 16:38 UTC, TopAcademy2022 commented on music-store/Models/Entities/VinylRecord.cs
> +		private readonly Logger? _logger;
Move in another class. Create base class for models.

2024-11-28 16:38 UTC, TopAcademy2022 commented on music-store/Models/Entities/VinylRecord.cs
> +		public VinylRecord(Logger? logger = null)
See above.

2024-11-28 16:38 UTC, TopAcademy2022 commented on music-store/Models/Entities/VinylRecord.cs
> +		private string _name = null!;
Don't create fields.

2024-12-09 16:18 UTC, TopAcademy2022 requested changes

2024-12-09 16:18 UTC, TopAcademy2022 commented on Program/Program.cs
Revome file.

2024-12-09 16:18 UTC, TopAcademy2022 commented on music-store.sln
Request chages.

2024-12-09 16:18 UTC, TopAcademy2022 commented on music-store/Models/Entities/MusicBand.cs
Remove spaces.

2024-12-09 16:23 UTC, TopAcademy2022 submitted a review, later dismissed

2024-12-09 16:43 UTC, closed without merging